// GENERATED by the Plugins module — do not edit by hand.
// Aggregates every installed plugin into the tool pool and gateway registry.
// Each plugin runs against a capability object (lib/plugin-runtime.js): a
// namespace-scoped DB, a gateway function closed over its own binding, and
// a namespaced logger. Plugin code never receives env.

import { pluginApi, wrapGatewayModes } from '../lib/plugin-runtime.js';

const BINDINGS = {};
const TABLES = {};

export const pluginTools = {
};

export const pluginGateways = {
};
